### ISSUE TITLE
Failed with HTTP 500 when TLS 1.2 enforced

### ISSUE THREAD

**Issue by Napsty** [slauger/check_netscaler_gateway#6]
Hi @slauger 

On the Netscaler side old SSL/TLS protocols SSLv3, TLS1.0 and TLS1.1 were disabled. 
After this, the plugin returns the following error:

```
NetScaler Gateway CRITICAL - request to https://mycitrix.example.com/Citrix/STORE_IDWeb/cgi/login failed with HTTP 500
```

In debug mode, the following error can be seen:

```
SSL connect attempt failed error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure at /usr/share/perl5/LWP/Protocol/http.pm line 47.
```

Looks like lwp wants to use SSLv3 and can't handle TLS 1.2 only?

**Comment by slauger** [comment]
LWP can handle TLS 1.2 without any problems. i think this might be related to your perl installation/distribution. Can you tell us something about your environment (OS, Perl Version, ...)?

Maybe your perl distribution can not handle your configured cipher suites on the NetScaler? How does your configuration look like here?

**Comment by Napsty** [comment]
Wow, you responded fast.

Yes, I was just checking this and was able to run the plugin fine from a Debian 9 (Stretch).

Differences:

| | Non-Working  | Working |
|-------------| ------------- | ------------- |
| OS | Ubuntu Xenial  | Debian Stretch  |
| Perl Version | 5.22.1  | 5.24.1  |
| LWP Version | 6.06-2  | 6.06-2  |
| OpenSSL Version | 1.0.2g  | 1.1.0l  |

So I think it's because of the OpenSSL version. 

I will update the OS. Thanks for your quick comment!

**Comment by Napsty** [comment]
For future visitors with the same problem: I described how to solve this problem with outdated OpenSSL libraries and an old Net::SSLeay module without having to upgrade the OS: https://www.claudiokuenzler.com/blog/1017/perl-lwp-unable-connect-tls-1.2-url-fail-sslv3-alert-handshake-failure

**Comment by slauger** [comment]
Good job, thank you! 👍
